# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2146fa4eaad5a4eeb2357bb04ab3ea9220b785bdf73860094064adc2132b4e05cb8834b1c5e864527c5ac56d551ca7852fcd9224c98b254e565ee302ee470c4

test:
  secret_key_base: 744ce8155e4193da0076c99513f586b598dbcbecb6e271ddc6a5256c1ca2d5b159cdee6596c4b22022b882e91c017c1d338666d05d05f2a2fac8ec9ee77cf311

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
